apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.serviceName | dump }}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: test.yaml, ggshield.yaml
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
